import "../globals.css";

export const metadata = {
    title: "Auth",
    description: "Generated by create next app",
};

export default function AuthLayout({children}) {
    return (
        <html lang="en">
        <body>
        {children}
        </body>
        </html>
    );
}