import MultiSidebar from "@/app/perfil/components/Sidebar";

export const metadata = {
    title: "Perfil",
    description: "Generated by create next app",
};

export default function PropertiesLayout({children}) {
    return (
        <main className={'flex'}>
            <MultiSidebar/>
            {children}
        </main>
    );
}