export const metadata = {
    title: "Perfil",
    description: "Generated by create next app",
};

export default function PropertiesLayout({children}) {
    return (
        <main>
            {children}
        </main>
    );
}