export const metadata = {
    title: "Regístrate",
    description: "Generated by create next app",
};

export default function RegisterLayout({children}) {
    return (
        <main>
            <div id="page">{children}</div>
        </main>
    );
}
