export const metadata = {
    title: "Add Property",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <main>
            <div id={'page'}>
                {children}
            </div>
        </main>
    );
}
