export const metadata = {
    title: "Indices de Precios",
    description: "Generated by create next app",
};

export default function PriceIndexLayout({children}) {
    return <main>{children}</main>;
}
