export const metadata = {
    title: "login",
    description: "Generated by create next app",
};

export default function LoginLayout({children}) {
    return (
        <main>
            <div id="page">{children}</div>
        </main>
    );
}
