export const metadata = {
    title: "Contactanos",
    description: "Generated by create next app",
};

export default function ContactUsLayout({children}) {
    return (
        <main className=" bg-[#EEEEEE]">
            <div id="page">{children}</div>
        </main>
    );
}
