export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ContactUsLayout({ children }) {
  return (
    <main className=" bg-[#EEEEEE]">
      <div id="page">{children}</div>
    </main>
  );
}
