"use client";
import Image from "next/image";
import { Label, Textarea, TextInput } from "flowbite-react";
import Head from "next/head";

export const metadata = {
  title: "Contactanos :)",
  description: "Generated by create next app",
};

export default function Contactus() {
  return (
    <section id={"contactus"} className="flex justify-between px-20 py-5">
      <div className=" space-y-5">
        <h2 className=" text-5xl font-bold">Contactanos</h2>
        <p className=" text-neutral-400 w-64">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error nam
          delectus excepturi facilis necessitatibus nesciunt provident non
          tempore quos sunt.
        </p>
        <ul className="[&>li]:flex [&>li]:items-center [&>li]:space-x-3 [&>li>i]:text-lg space-y-4">
          <li>
            <i class="bi bi-envelope-fill"></i>
            <p>tommy@gmail.com</p>
          </li>
          <li>
            <i class="bi bi-telephone-fill"></i> <p>809-241-2028</p>
          </li>
        </ul>
      </div>

      <div className={"bg-white shadow w-[750px]  py-10 px-10 rounded-lg"}>
        <div className="flex space-x-5">
          <div className="mb-2 block  w-full">
            <label className={"text-white text-md font-bold"}>Nombre</label>
            <TextInput
              id="email4"
              placeholder="Pedro"
              sizing={"lg"}
              required
              type="text"
            />
          </div>
          <div className="mb-2 block  w-full">
            <label className={"text-white text-md font-bold"}>Apellido</label>
            <TextInput
              id="email4"
              placeholder="Almonte"
              sizing={"lg"}
              required
              type="text"
            />
          </div>
        </div>
        <div className=" flex space-x-5">
          <div className="mb-2 block w-full">
            <label className={"text-white text-md font-bold"}>Email</label>
            <TextInput
              id="email4"
              placeholder="example@gmail.com"
              required
              sizing={"lg"}
              type="email"
            />
          </div>
          <div className="mb-2 block w-full">
            <label className={"text-white text-md font-bold"}>Telefono</label>
            <TextInput
              id="email4"
              placeholder="8097862310"
              sizing={"lg"}
              required
              type="number"
            />
          </div>
        </div>

        <div className="w-full pb-5" id="textarea">
          <div className="mb-2 block w-full">
            <label className={"text-white text-md font-bold"}>Tu mensaje</label>
          </div>
          <Textarea
            id="comment"
            placeholder="Message"
            required
            rows={4}
            cols={50}
          />
        </div>
        <div className={"flex "}>
          <button className="bg-[#0DEDFF] p-3 text-black rounded-tl-xl rounded-br-xl hover:bg-[#0DEDFF]/80">
            Contactar
          </button>
        </div>
      </div>
    </section>
  );
}
